FROM ubuntu:bionic 
#image ubuntu

#mise a jour image et installation de bind9 
RUN apt-get update \
  && apt-get install -y \
  bind9 \
  bind9utils \
  bind9-doc 

# activation IPv4
RUN sed -i 's/OPTIONS=.*/OPTIONS="-4 -u bind"/' /etc/default/bind9

# copie des fichiers de configuration de la machine locale vers image docker
COPY named.conf /etc/bind/ 
COPY l2-5.ephec-ti.be /etc/bind/ 

#ouverture du port 53 en udp de image
EXPOSE 53/udp 

#demarrage du serveur dns 
CMD named -g