# On prend une image ubuntu comme base
FROM ubuntu:latest

# On installe ce qu'il faut sur l'image
RUN apt-get update \
  && apt-get install -y \
  samba \
  systemctl \
  nano \
  vim

# On initie les fichiers de partages et le compte linux de l'utilisateur classique
RUN mkdir -p /home/share
RUN chmod 777 /home/share 
RUN chgrp sambashare /home/share
RUN useradd -M -d /home/share/user1 -s /usr/sbin/nologin -G sambashare user1
RUN mkdir /home/share/user1
RUN chown user1:sambashare /home/share/user1
RUN chmod 2770 /home/share/user1

RUN echo classic123 | smbpasswd -a user1 & echo classic123
RUN echo classic123 | pdbedit -a user1 & echo classic123

# On initie les fichiers de partages et le compte linux de l'utilisateur admin
RUN useradd -M -d /home/share/smbadmin -s /usr/sbin/nologin -G sambashare smbadmin
RUN mkdir /home/share/smbadmin
RUN chown smbadmin:sambashare /home/share/smbadmin
RUN chmod 2770 /home/share/smbadmin

RUN echo adminabc | smbpasswd -a smbadmin & echo adminabc
RUN echo adminabc | pdbedit -a smbadmin & echo adminabc

# On copie le fichier de configuration de samba 
COPY smb.conf /etc/samba

# IMPORTANT : Exposer les ports qui sont nécessaires au bon fonctionnement du cloud
EXPOSE 445/TCP
EXPOSE 139/TCP

# On restart le service samba pour appliquer les modifs
# CMD service smbd restart 

ENTRYPOINT ["tail", "-f", "/dev/null"]




