FROM romeoz/docker-apache-php

RUN apt install apache2
RUN apt-get update -y && apt-get install -y nano vim
RUN apt-get install -y dnsutils net-tools iputils-ping

COPY /WWW/site_dynamique/index.php /var/www/b2b/index.php
COPY /SITES_AVAILABLE/site_dynamique.conf /etc/apache2/sites-available/b2b.conf
COPY /WWW/html/index.html /var/www/index.html
COPY /SITES_AVAILABLE/www.conf /etc/apache2/sites-available/www.conf

COPY apache2.conf /etc/apache2/apache2.conf

RUN a2ensite b2b.conf
RUN a2ensite www.conf
RUN a2ensite www-ssl.conf
RUN a2enmod headers
RUN a2enmod rewrite
RUN service apache2 restart